// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBraMr4AFB2pWFdQfXzfzkcmEqxfe8Idjk',
    appId: '1:1001482037636:android:a889f453df2d6d9925d5d1',
    messagingSenderId: '1001482037636',
    projectId: 'invoice-generator-4439',
    storageBucket: 'invoice-generator-4439.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0UIM7wAhZ73WzkEE-wK1e7KfwTp3Ajpw',
    appId: '1:1001482037636:ios:694f7cb8f8f604ae25d5d1',
    messagingSenderId: '1001482037636',
    projectId: 'invoice-generator-4439',
    storageBucket: 'invoice-generator-4439.firebasestorage.app',
    iosBundleId: 'com.superio.invoiceGenerator',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKzOPoqYIV1i3blIFCesGykqpmX1COavs',
    appId: '1:1001482037636:web:d02dceef5c7f683825d5d1',
    messagingSenderId: '1001482037636',
    projectId: 'invoice-generator-4439',
    authDomain: 'invoice-generator-4439.firebaseapp.com',
    storageBucket: 'invoice-generator-4439.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0UIM7wAhZ73WzkEE-wK1e7KfwTp3Ajpw',
    appId: '1:1001482037636:ios:694f7cb8f8f604ae25d5d1',
    messagingSenderId: '1001482037636',
    projectId: 'invoice-generator-4439',
    storageBucket: 'invoice-generator-4439.firebasestorage.app',
    iosBundleId: 'com.superio.invoiceGenerator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKzOPoqYIV1i3blIFCesGykqpmX1COavs',
    appId: '1:1001482037636:web:93a8145bc2d0118f25d5d1',
    messagingSenderId: '1001482037636',
    projectId: 'invoice-generator-4439',
    authDomain: 'invoice-generator-4439.firebaseapp.com',
    storageBucket: 'invoice-generator-4439.firebasestorage.app',
  );

}